# Generated by Django 4.2.16 on 2024-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic_updated_by_topic_updated_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, default='board_images/default.jpg', null=True, upload_to='board_images/'),
        ),
    ]
