# Generated by Django 4.2.16 on 2024-11-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, default='board_images/default.jpg', null=True, upload_to='media/board_images/'),
        ),
    ]
