# Generated by Django 4.2.16 on 2024-11-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_board_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='forummodel',
        ),
    ]
