# Generated by Django 5.1.3 on 2024-11-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_rename_board_topic_forumboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='forumtopic',
        ),
    ]
