# Generated by Django 5.1.3 on 2024-11-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_rename_topic_post_forumtopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='forumtopic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='forumboard',
            new_name='board',
        ),
    ]
