# Generated by Django 5.1.3 on 2024-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_rename_description_forummodel_forumdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='ForumImage',
            field=models.ImageField(blank=True, default='board_images/bootstrap.png', null=True, upload_to='media/board_images/'),
        ),
    ]
