# Generated by Django 5.1.3 on 2024-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_rename_topic_forumsectionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumsectionmodel',
            old_name='subject',
            new_name='SectionSubject',
        ),
        migrations.AlterField(
            model_name='forummodel',
            name='ForumImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/board_images/'),
        ),
    ]
