# Generated by Django 5.1.3 on 2024-12-03 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_alter_commentmodel_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comt', to='boards.forumsectionmodel'),
        ),
    ]
