# Generated by Django 5.1.3 on 2024-12-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_alter_commentmodel_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='message',
            new_name='massg',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='topic',
            new_name='section',
        ),
    ]
